destination: /Users/wjgan/Documents/wjgan7.github.io/_site

plugins:
  - jekyll-seo-tag

# Jekyll Seo Tag
url: https://wjgan.com
social:
  links:
    - https://linkedin.com/in/wjgan
    - https://github.com/wjgan7
